# Mini-Project 1 - Used Cars in the USA - SVM & LR Classification
#### By: David Wei, Sophia Wu, Dhruba Dey, Queena Wang

## Introduction
In this section we will continue using our used car dataset and be building out a classification model using Logistic Regression (LR) and Support Vector Machines (SVM). 

In [57]:
#importing libraries and reading in file
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') #ignoring warnings
import missingno as msno

#plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns
from plotnine.data import economics
from plotnine import ggplot, aes, geom_line

#general sklearn libraries
from scipy.stats import trim_mean, kurtosis
from scipy.stats.mstats import mode, gmean, hmean
import ptitprince as pt
import sklearn.preprocessing as preprocessing
import sklearn.model_selection as cross_validation
import sklearn.linear_model as linear_model
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import ShuffleSplit
from sklearn.preprocessing import StandardScaler #for scaling

#logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt
from sklearn.model_selection import cross_val_score

For convenience and clarity, we have exported all of the data tidying and cleaning we have applied to our original dataset from our initial EDA workbook as an importable file. This will allow us to simply pick up on where we left off without cluttering our notebook with all prior code. For reference, please refer to the following [github link](https://github.com/chee154/ml-Py-used_cars/blob/main/Used_Car_Lab_1_DataVisualization.ipynb) where all work has been contained.

In [2]:
df_raw = pd.read_csv(r'E:\Data Files\used_cars_data_cleaned.csv')
print('# of Records: '+str(len(df_raw)))
print('# of Columns: '+str(df_raw.shape[1]))

# of Records: 697989
# of Columns: 18


## Data Tidying

#### Addressing Empty Values
<b>NOTE</b>: First time running the logistic regression model returned an error: 
<br>
*ValueError: Input contains NaN, infinity or a value too large for dtype('float64').*
<br>
Therefore, we will fix this by once again removing any strangling NA records from our dataset.

In [3]:
df_cleaned = df_raw.copy()
df_cleaned = df_cleaned.dropna()
print(len(df_cleaned))
print('# of Records Removed: '+str(len(df_raw)-len(df_cleaned)))

697881
# of Records Removed: 108


#### Cleaning up final dataframe
After the initial EDA, we will make the appropriate adjustments to our dataset based on our findings. To begin, let's get look at the relationship between **'length'** and **'height'** due to it's high correlation.

In [129]:
df_test = df_cleaned.copy()
print(df_test.shape[1])

if df_test['length'].equals(df_test['height']) == True:
    print('they are the same... dropping one')
    df_test = df_test.drop(columns='height')
    print(df_test.shape[1])
else: 
    print('they are not the same')

18
they are the same... dropping one
17


## Data Transformations for Modeling

In [132]:
df_test['rank']=df_test['price'].rank()

In [134]:
df_test['rank_pct']= df_test['price'].rank(pct=True)

In [139]:
df_test[['price', 'rank', 'rank_pct']].sort_values(by=['rank'])

price      rank  rank_pct
357243      484.0       2.0  0.000003
357242      484.0       2.0  0.000003
357218      484.0       2.0  0.000003
345470      490.0       4.0  0.000006
82576       495.0      11.5  0.000016
...           ...       ...       ...
218024  1244996.0  697877.0  0.999994
501812  1499999.0  697878.0  0.999996
56656   2698500.0  697879.0  0.999997
42212   3195000.0  697880.0  0.999999
340170  3299995.0  697881.0  1.000000

[697881 rows x 3 columns]

In [160]:
def apply_class_func(price):
    if price >= .75:
        return "A"
    elif .5 <= price <= .74:
        return "B"
    elif .25 <= price <= .49:
        return "C"
    elif price <= .25:
        return "D"

In [161]:
df_test['price_cat']=df_test['rank_pct'].apply(apply_class_func)

In [163]:
df_test.groupby(['price_cat']).size()

price_cat
A    174898
B    167554
C    167491
D    174472
dtype: int64

In [164]:
print(df_test[['price', 'rank', 'rank_pct','price_cat']])

          price      rank  rank_pct price_cat
0       14639.0  123784.0  0.177371         D
1       32000.0  552264.0  0.791344         A
2       23723.0  394672.0  0.565529         B
3       22422.0  366562.0  0.525250         B
4       29424.0  508197.5  0.728201         B
...         ...       ...       ...       ...
697984  17836.0  227445.0  0.325908         C
697985  20700.0  324274.0  0.464655         C
697986  17700.0  224104.0  0.321121         C
697987  40993.0  643238.5  0.921702         A
697988  19900.0  299409.0  0.429026         C

[697881 rows x 4 columns]


#### Transforming Response Variable from Continuous to Categorical
Since our main interest in this dataset is the 'price' of a vehicle, we will transform our continuous price attribute into a categorical one by grouping all car prices into the following:
* "<5000"          : price < 5000
* "5000-10000"     : 5000 <= price <= 10000
* "10000-15000"    : 10000 < price <= 15000
* "15000-20000"    : 15000 < price <= 20000
* "20000-25000"    : 20000 < price <= 25000
* "25000 and over" : price > 25000

In [4]:
price_group = []
for price in df_cleaned["price"]:
    if price < 5000:
        price_group.append("<5000")
    elif 5000 <= price <= 10000:
        price_group.append("5000-10000")
    elif 10000 < price <= 15000:
        price_group.append("10000-15000")
    elif 15000 < price <= 20000:
        price_group.append("15000-20000")
    elif 20000 < price <= 25000:
        price_group.append("20000-25000")
    else:
        price_group.append("25000 and over")

In [5]:
df_price_group = df_cleaned.copy()
df_price_group["price_group"] = price_group
del df_price_group["price"]
print(df_price_group['price_group'])

0            10000-15000
1         25000 and over
2            20000-25000
3            20000-25000
4         25000 and over
               ...      
697984       15000-20000
697985       20000-25000
697986       15000-20000
697987    25000 and over
697988       15000-20000
Name: price_group, Length: 697881, dtype: object


In [165]:
df_price_group.groupby(['price_group']).size()

price_group
10000-15000        96001
15000-20000       172368
20000-25000       115254
25000 and over    268595
5000-10000         40482
<5000               5181
dtype: int64

#### OneHotEncoding
Once the data has been imported and cleaned, we will work on transforming our dataset to be more useful for our classification models. To start we will first one-hot encode all of our categorical (object) datatypes as numbers.

In [8]:
def number_encode_features(df_price_group):
    result = df_price_group.copy()
    encoders = {}
    for column in result.columns:
        if result.dtypes[column] == np.object or result.dtypes[column]==np.bool:
            encoders[column] = preprocessing.LabelEncoder()
            result[column] = encoders[column].fit_transform(result[column])
    print('Columns converted: '+str(encoders))
    return result

Below shows a snap shot of what the final data looks like after categorical data has been encoded.
You can see the body type is in a numerical representation, instead of a string (object) type, before being encoded.
<br>
- Below shows a snap shot of what the final data looks like after categorical data has been encoded.
- You can see the body type is in a numerical representation, instead of a string (object) type, before being encoded.

In [9]:
encoded_data = number_encode_features(df_price_group)
encoded_data

Columns converted: {'body_type': LabelEncoder(), 'frame_damaged': LabelEncoder(), 'has_accidents': LabelEncoder(), 'is_new': LabelEncoder(), 'price_group': LabelEncoder()}


body_type  city_fuel_economy  daysonmarket  engine_displacement  \
0               6               27.0            55               1500.0   
1               1               18.0            36               3500.0   
2               5               18.0            27               3600.0   
3               5               15.0            27               3600.0   
4               5               18.0            24               3600.0   
...           ...                ...           ...                  ...   
697984          5               26.0            32               1400.0   
697985          5               26.0            17               2500.0   
697986          6               26.0            17               2500.0   
697987          4               18.0            89               3500.0   
697988          5               26.0            17               2500.0   

        frame_damaged  has_accidents  height  highway_fuel_economy  \
0                   0              0    57.6                  36.0   
1                   0              0    55.1                  24.0   
2                   0              0    70.7                  27.0   
3                   0              1    69.9                  22.0   
4                   0              0    69.3                  25.0   
...               ...            ...     ...                   ...   
697984              0              0    66.0                  31.0   
697985              0              0    66.4                  32.0   
697986              0              0    57.9                  37.0   
697987              0              0    70.6                  23.0   
697988              0              0    68.1                  33.0   

        horsepower  is_new  length  maximum_seating  mileage  owner_count  \
0            160.0       0    57.6              5.0  42394.0          1.0   
1            311.0       0    55.1              4.0  62251.0          1.0   
2            310.0       0    70.7              8.0  36410.0          1.0   
3            281.0       0    69.9              8.0  36055.0          1.0   
4            295.0       0    69.3              5.0  25745.0          1.0   
...            ...     ...     ...              ...      ...          ...   
697984       138.0       0    66.0              5.0   7444.0          1.0   
697985       170.0       0    66.4              5.0  20160.0          1.0   
697986       179.0       0    57.9              5.0  62138.0          1.0   
697987       278.0       0    70.6              5.0  20009.0          1.0   
697988       170.0       0    68.1              7.0  22600.0          1.0   

        seller_rating  width  year  price_group  
0            3.447761   73.0  2018            0  
1            2.800000   81.5  2018            3  
2            3.447761   78.6  2018            2  
3            3.447761   78.5  2017            2  
4            3.447761   84.8  2018            3  
...               ...    ...   ...          ...  
697984       4.533333   69.9  2019            1  
697985       4.333333   80.0  2017            2  
697986       4.333333   72.0  2018            1  
697987       5.000000   75.2  2017            3  
697988       4.333333   72.4  2017            1  

[697881 rows x 18 columns]

Referncing our transformed variable 'price_group' as an int to it's original string value for future analysis and interpretation

In [41]:
print(df_final.groupby(['price_group']).size())
print('-----------------------------------------')
print(df_price_group.groupby(['price_group']).size())

price_group
0     96001
1    172368
2    115254
3    268595
4     40482
5      5181
dtype: int64
-----------------------------------------
price_group
10000-15000        96001
15000-20000       172368
20000-25000       115254
25000 and over    268595
5000-10000         40482
<5000               5181
dtype: int64


Now we are ready for some model building!

In [26]:
df_final = encoded_data.copy()
print('# of Records: '+str(len(df_final)))
print('# of Columns: '+str(df_final.shape[1]))
print()
print(df_final.dtypes)

# of Records: 697881
# of Columns: 18

body_type                 int32
city_fuel_economy       float64
daysonmarket              int64
engine_displacement     float64
frame_damaged             int64
has_accidents             int64
height                  float64
highway_fuel_economy    float64
horsepower              float64
is_new                    int64
length                  float64
maximum_seating         float64
mileage                 float64
owner_count             float64
seller_rating           float64
width                   float64
year                      int64
price_group               int32
dtype: object


## Training and Testing Split
Once our dataset ready for modeling, we will move on to our next steps of splitting up our data. For our dataset, we will use a 70:30 split that roughly leaves our training set with 488k records and test set with the remainder (209k records). We will then apply a 3-fold Cross Validation with a seed of 42 because it (42) is the answer to the ultimate question of life, the universe, and everything.
<br><br>
Our resposne variable will be price, more specifically the price group ('price_group') a car falls in.

In [11]:
if 'price_group' in df_final:
    y = df_final['price_group'].values # get the labels we want
    del df_final['price_group'] # get rid of the class label
    X = df_final.values # use everything else to predict!
print(y)
print()

num_cv_iterations = 3
num_instances = len(y)
cv_object = ShuffleSplit(n_splits=num_cv_iterations,random_state=42, test_size= 0.3)     
print(cv_object)

[0 3 2 ... 1 3 1]

ShuffleSplit(n_splits=3, random_state=42, test_size=0.3, train_size=None)


In [49]:
print('Count of Training Set: '+str(len(train_indices)))
print('Count of Test Set: '+ str(len(test_indices)))

Count of Training Set: 488516
Count of Test Set: 209365


## Logistic Regression

In [12]:
lr_clf = LogisticRegression(penalty='l2', C=1.0, class_weight=None, solver='liblinear' ) 

In [13]:
iter_num=0

for train_indices, test_indices in cv_object.split(X,y): 
    # I will create new variables here so that it is more obvious what 
    # the code is doing (you can compact this syntax and avoid duplicating memory,
    # but it makes this code less readable)
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    # train the reusable logisitc regression model on the training data
    lr_clf.fit(X_train,y_train)  # train object
    y_hat = lr_clf.predict(X_test) # get test set precitions

    # now let's get the accuracy and confusion matrix for this iterations of training/testing
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print("====Iteration",iter_num," ====")
    print("accuracy", acc )
    print("confusion matrix\n",conf)
    iter_num+=1

====Iteration 0  ====
accuracy 0.5940104602010843
confusion matrix
 [[ 8282 17791     4  1384  1359     0]
 [ 2907 37266     1 11376   278     1]
 [  544 17526     7 16295    70     2]
 [  163  6378     2 74023    14     3]
 [ 4853  2435     0    69  4786     0]
 [   74    59     0     2  1410     1]]
====Iteration 1  ====
accuracy 0.5931268359085807
confusion matrix
 [[ 8003 17858     2  1482  1220     2]
 [ 2751 37299     1 11422   272     0]
 [  490 17589     1 16732    59     2]
 [  180  6272     1 74079    19     2]
 [ 4884  2305     0    81  4793     7]
 [   82    32     0     2  1436     5]]
====Iteration 2  ====
accuracy 0.5915076540969121
confusion matrix
 [[ 7979 18043     9  1418  1275     3]
 [ 2804 37257    24 11597   260     2]
 [  542 17366    11 16641    77     4]
 [  210  6342     1 73901    21     2]
 [ 4790  2460     0    76  4692     5]
 [   67    66     0     0  1419     1]]


In [53]:
# here we can change some of the parameters interactively
from ipywidgets import widgets as wd

def lr_explor(cost):
    lr_clf = LogisticRegression(penalty='l2', C=cost, class_weight=None,solver='liblinear') # get object
    accuracies = cross_val_score(lr_clf,X,y=y,cv=cv_object) # this also can help with parallelism
    print(accuracies)

wd.interact(lr_explor,cost=(0.001,5.0,0.05),__manual=True)

interactive(children=(FloatSlider(value=2.451, description='cost', max=5.0, min=0.001, step=0.05), Output()), …

<function __main__.lr_explor(cost)>

### LR - Analysis & Intepretations

**Weights *before* normalization:**
<br>
We can see that even before we normalized our dataset the **'mileage'** and **'frame_damaged'** attribute showns an extremely strong weight in regards to the price (and group) of a vehicle. Additionally, we can see that **'is_new'** has a particularly strong negative weight in regards to price, this can be interpreted that this variable less of an effect on pricing, which makes sense since prior analysis (lab 1) showed us that 99% of our data is used cars. 

In [54]:
weights = lr_clf.coef_.T # take transpose to make a column vector
variable_names = df_final.columns
for coef, name in zip(weights,variable_names):
    print(name, 'has weight of', coef[0])

body_type has weight of 0.0057163416525310715
city_fuel_economy has weight of 0.008468206076927606
daysonmarket has weight of 0.00026206704928768027
engine_displacement has weight of 0.00016257524473640075
frame_damaged has weight of 3.420932842151794e-05
has_accidents has weight of 0.0009125828229602852
height has weight of -0.02536604331004255
highway_fuel_economy has weight of 0.033091731256355165
horsepower has weight of -0.010847141122508433
is_new has weight of -2.3644937572113936e-05
length has weight of -0.02536604331004255
maximum_seating has weight of 0.00043665006943592
mileage has weight of 2.088535312684802e-05
owner_count has weight of 0.0036910533862481074
seller_rating has weight of -0.0013893811373334307
width has weight of 0.0004954509109703305
year has weight of 0.00047962953048214706


**Weights *after* normalization:**
<br>
Once the weights have been normalized as shown below 

In [83]:
# scale attributes by the training set
scl_obj = StandardScaler()
scl_obj.fit(X_train)

X_train_scaled = scl_obj.transform(X_train) # apply to training
X_test_scaled = scl_obj.transform(X_test) # apply those means and std to the test set (without snooping at the test set values)

# train the model just as before
lr_clf = LogisticRegression(penalty='l2', C=0.05, solver='liblinear') # get object, the 'C' value is less (can you guess why??)
lr_clf.fit(X_train_scaled,y_train)  # train object

y_hat = lr_clf.predict(X_test_scaled) # get test set precitions

acc = mt.accuracy_score(y_test,y_hat)
conf = mt.confusion_matrix(y_test,y_hat)
print('accuracy:', acc )
print(conf )

accuracy: 0.6145726363050176
[[10011 16281   116   763  1556     0]
 [ 3074 37840   398 10404   228     0]
 [  474 17375   221 16531    40     0]
 [  123  5677    58 74573    46     0]
 [ 4485  1493     5    15  6025     0]
 [   27     0     0     0  1526     0]]


In [100]:
# sort these attributes and spit them out
zip_vars = zip(lr_clf.coef_.T,df_final.columns) # combine attributes
#zip_vars = sorted(zip_vars) this does not work since our expected value has 6 distinct groups

for coef, name in zip_vars:
    print(name, 'has weight of', coef[0]) # now print them out

body_type has weight of 0.0866878246447711
city_fuel_economy has weight of -0.6396807600296892
daysonmarket has weight of 0.0101849650015951
engine_displacement has weight of 0.08583712950560271
frame_damaged has weight of 0.0006613351249991328
has_accidents has weight of 0.04001650928425897
height has weight of 0.008054892005808624
highway_fuel_economy has weight of 1.0301979658227287
horsepower has weight of -0.9231363777396635
is_new has weight of -0.07040009675626192
length has weight of 0.008054892005808624
maximum_seating has weight of 0.04903695769244853
mileage has weight of 0.6221085747978092
owner_count has weight of 0.1103811763580796
seller_rating has weight of -0.06270892693260087
width has weight of 0.005805976522987003
year has weight of -0.09235570878852435


In [99]:
df_final['price_group'].unique()

array([0, 3, 2, 1, 4, 5])

In [97]:
print(lr_clf.coef_.T)

[[ 8.66878246e-02 -5.51634477e-02 -4.56715886e-02  2.33739202e-01
  -3.23264860e-02  7.72698416e-02]
 [-6.39680760e-01 -1.26097880e-01 -4.16812617e-01  1.45538110e+00
  -1.20765966e+00 -8.13981633e-01]
 [ 1.01849650e-02  2.67397531e-02 -6.11713637e-03 -1.40204270e-01
  -4.04370053e-02  1.13942763e-02]
 [ 8.58371295e-02  2.96728489e-01 -1.93977906e-01 -6.96789975e-02
  -5.92580017e-01 -2.86843352e-01]
 [ 6.61335125e-04 -6.74923642e-03 -1.01112131e-02 -3.74842466e-02
   1.55108949e-02  3.80139433e-02]
 [ 4.00165093e-02  5.17606828e-03  6.11150995e-03 -6.27312332e-02
   7.24584694e-02  3.84751321e-02]
 [ 8.05489201e-03 -1.55734915e-01 -1.76206881e-02  2.17536895e-01
  -2.45435960e-02 -2.62414574e-01]
 [ 1.03019797e+00 -3.94768002e-02 -5.62937006e-02 -1.18517244e+00
   1.30244527e+00  3.06951730e-01]
 [-9.23136378e-01 -1.33516862e+00 -4.22892068e-01  2.99399453e+00
  -9.81584455e-01 -1.37099271e+00]
 [-7.04000968e-02 -4.64597708e-02 -2.60674750e-02  4.45396976e-02
  -5.74705922e-02  4.6330

## Support Vector Machines